#!/usr/bin/env bash

if pgrep "swayidle" > /dev/null
then
    pkill swayidle
    echo "$LABEL" "Disabled"
else
    $(swaymsg exec "swayidle -w timeout 120 'swaylock -f -c 000000' \
        timeout 180 'swaymsg "output * dpms off"' \
            resume 'swaymsg "output * dpms on"' \
        before-sleep 'swaylock -f -c 000000'")

    echo "$LABEL" "Active"
fi

exit 0
